video:
  fps: 30   # frames per second of video
  thumbnail_scale: 0.6   # resize factor of video for labelling
  min_path_length: 5   # the minimum number of frames in a path to be considered valid
  conversion_factor: 0.072
  area_conversion: 0.005184  # area unit conversion

dimensions:
  video:
  - 1020       # x (of segmented arena video)
  - 832       # y (of segmented arena video)
  signal:
  - 20       # x (of segmented signal video)
  - 20       # y (of segmented signal video)
  arena:
  - 755       # left (distance from exit xy)
  - 370       # top (distance from exit xy)
  - 110       # right (distance from exit xy)
  - 365       # bottom (distance from exit xy)
  exit:
  - 20       # left (distance from exit xy)
  - 100       # top (distance from exit xy)
  - 60       # right (distance from exit xy)
  - 100       # bottom (distance from exit xy)
  centre: [200, 570, 620, 260]
  corners:
    - [119, 140]
    - [750, 158]
    - [756, 660]
    - [100, 653]
  exit_roi: [700, 300, 800, 500]
